### ISSUE TITLE
I got a bug.

### ISSUE THREAD

**Issue by awasthi** [opengbu/faculty#1]
A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; font-stretch: in' at line 1

insert into events (fac_id,name,other_details) VALUES ('7','9th International Conference on Heterogeneous Networking for Quality, Reliability, Security and Robustness','January 11–12, 2013,Greater Noida, India')

Filename: controllers/New_event.php

Line Number: 31

**Comment by Varun-garg** [comment]
I am unable to reproduce the above bug

**Comment by awasthi** [comment]
Did you work on final output report of naac?

**Comment by Varun-garg** [comment]
I added it it just now.
